### PR TITLE
Generalization

### PR DESCRIPTION
**Pull request by osmannkartall**

### CODE REVIEW

**Comment by osmannkartall** [comment]
[9abdcf5](https://github.com/osmannkartall/knowzone/pull/162/commits/9abdcf5041d4b7241055db5a66b54b087b811741) is based on [this documentation](https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples/test-runners#jest)

**Comment by osmannkartall** [comment]
[70d89a5](https://github.com/osmannkartall/knowzone/pull/162/commits/70d89a5faae71b792f9f8231f77555af41f9ca8c) -> https://github.com/facebook/jest/issues/4997

**Comment by osmannkartall** [comment]
Currently, authenticated users can only view their own posts.

**Review by yusufakdas — APPROVED** [review]

**Comment by osmannkartall** [comment]
[add mongo db integration test](https://github.com/osmannkartall/knowzone/pull/162/commits/e2b45db59921f3b18ce8fc003ecc99d51ad8457b) --> Actually, we tested the schemas in isolation. Thus, these are unit tests.

**Pull request merged**
